### ISSUE TITLE
Fix server environment variables

### ISSUE THREAD

**Issue by roflolilolmao** [HE-Arc/Affinity#5]
We changed database.yml to use environment variables for default host and user so that it works both on local and deploy. Problem is, the server now reads

`could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`

If we change database.yml from

`host: <%= ENV["POSTGRES_HOST"] %>
user: <%= ENV["POSTGRES_USERNAME_DEFAULT"] %>`

to

`host: postgres
user: postgres`

it works fine. The environment variables must be the cause. Tried adding them in ~/.bash_profile but it does not work.

**Comment by greut** [comment]
@roflolilolmao  :wink: https://github.com/HE-Arc/demo-rails-application/blob/master/config/database.yml
